### ISSUE TITLE
Including http libraries

### ISSUE THREAD

**Issue by rogsmith** [le0pard/elixir_v8#2]
Have you had any success including node libraries like 'request' or others? I would like to add the ability to make http calls? what about jquery?

**Comment by rogsmith** [comment]
of even better any suggestions on using elixir functions from within the eval'd javascript?

**Comment by le0pard** [comment]
Inside readme I have example to add JS libs in all v8 in start time.

I don't use node.js libs in v8. If I need node.js - I use node.js.

Jquery need DOM - v8 and node.js is not have DOM.

I don't call elixir functions inside v8 engine. It doesn't make sense, because it broke isolation level for usage, as I see this lib.

**Comment by rogsmith** [comment]
any suggestions for js libraries to include that allow for http calls?

**Comment by le0pard** [comment]
no, I don't have any suggestion.
